name: ohmyg0sh
description: Lightweight Dart package for detecting possible API key or secret leaks using regex signatures.
version: 1.69.777
repository: https://github.com/username/ohmyg0sh
issue_tracker: https://github.com/username/ohmyg0sh/issues
homepage: https://github.com/username/ohmyg0sh
topics:
  - security
  - scanner
  - apk
  - regex
  - dart

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.9.1
  args: ^2.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  assets:
    - config/regexes.json
    - config/notkeyhacks.json


executables:
  ohmyg0sh: ohmyg0sh
