name: ohmyg0sh
description: APK security scanner that detects hardcoded API keys and credentials before they reach production.
version: 1.69.777
repository: https://github.com/mathtechstudio/ohmyg0sh
issue_tracker: https://github.com/mathtechstudio/ohmyg0sh/issues
homepage: https://github.com/mathtechstudio/ohmyg0sh
topics:
  - security
  - scanner
  - apk
  - regex
  - dart

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  assets:
    - config/regexes.json
    - config/notkeyhacks.json

# CLI executable - users can run 'ohmyg0sh' after pub global activate
executables:
  ohmyg0sh: